name: Deploy Vigenesia
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deployment Vigenesia
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          port: 22
          command: cd /home/pi/Projects/vigenesia && git pull origin main